import org.apache.tools.ant.filters.ReplaceTokens
import work.lclpnet.build.task.GithubDeploymentTask

plugins {
    alias(libs.plugins.fabric.loom)
    alias(libs.plugins.maven.publish)
    alias(libs.plugins.gradle.build.utils)
    alias(libs.plugins.java)
}

Properties props = buildUtils.loadProperties('publish.properties')

group = project.maven_group
version = "${project.mod_version}+${libs.versions.minecraft.get()}"

def modId = project.mod_id
def javaVersion = libs.versions.java.get().toInteger()

base {
    archivesName = modId
}

repositories {
    mavenCentral()

    maven {
        url "https://repo.lclpnet.work/repository/internal"
    }

    // ModMenu
    maven {
        url "https://maven.terraformersmc.com/releases/"
    }

    // cloth-config
    maven {
        url "https://maven.shedaniel.me/"
    }
}

dependencies {
    minecraft(libs.minecraft)
    implementation(libs.fabric.loader)
    implementation(libs.fabric.api)

    api(libs.cloth.config) {
        exclude(group: libs.fabric.api.get().group)
    }

    implementation(libs.modmenu)

    /* other Java dependencies */
    implementation(libs.jsr305)

    def includeImpl = { dep ->
        implementation(dep)
        include(dep)
    }

    includeImpl(libs.org.json)
    includeImpl(libs.json.config4j)

    testImplementation(libs.junit.jupiter)
    testImplementation(libs.junit.jupiter.params)
    testRuntimeOnly(libs.junit.jupiter.engine)
}

test {
    useJUnitPlatform()
}

processResources {
    def tokens = [
            "version": project.version.toString(),
            "loader_version": libs.versions.fabric.loader.get(),
            "minecraft_compat": project.minecraft_compat,
            "java_version": javaVersion.toString()
    ]

    inputs.properties(tokens)

    filesMatching("fabric.mod.json") {
        expand(tokens)
    }

    filesMatching("*.mixins.json") {
        filter(ReplaceTokens, beginToken: '${', endToken: '}', tokens: tokens)
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release.set(javaVersion)
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.toVersion(javaVersion)
    targetCompatibility = JavaVersion.toVersion(javaVersion)
}

jar {
    from("LICENSE.md") {
        rename { "${it}_${project.base.archivesName.get()}"}
    }
}

def env = System.getenv()

tasks.register("github", GithubDeploymentTask) {
    dependsOn tasks.jar

    config {
        token = env.get("GITHUB_TOKEN")
        repository = env.get("GITHUB_REPOSITORY")
    }

    release {
        title = "[${libs.versions.minecraft.get()}] Creative Power $project.version"
        tag = project.version
    }

    assets.add(tasks.jar.archiveFile.get())
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.base.archivesName.get()

            from components.java

            pom {
                name = 'Creative Power'
                description = 'Fabric Client mod for boosting a builders efficiency.'
            }
        }
    }

    buildUtils.setupPublishRepository(repositories, props)
}